#!/bin/bash 
#PBS -l walltime=01:00:00
#PBS -l mem=192GB 
#PBS -l ncpus=48
#PBS -l jobfs=1GB 
#PBS -l storage=gdata/hh5+gdata/gb02+scratch/gb02+gdata/rv74 
#PBS -q express
#PBS -P gb02
#PBS -o /home/548/pag548/code/aus-historical-solar-droughts/qsub_calc.out
#PBS -e /home/548/pag548/code/aus-historical-solar-droughts/qsub_calc.err

cd /home/548/pag548/code/aus-historical-solar-droughts

source ./env.sh

python code/python/scripts/concurrent_test.py


